administrasi/administrasi/urls.py
from django.contrib import admin
from django.urls import path, include
from surat_menyurat import views

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('home/', views.home, name='home'),    
    path('surat/', include('surat_menyurat.urls', namespace="surat")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

administrasi/surat_menyurat/urls.py
from django.urls import path, include
from . import views

app_name ='surat_menyurat'

urlpatterns = [
  path('instansi-list/', views.InstansiListView.as_view(), name='instansi_list'),
  path('instansi-form/', views.InstansiCreateView.as_view(), name='instansi_form'),
  path('instansi-delete/<int:id>', views.InstansiDeleteView.as_view(), name='instansi_delete'),
  path('instansi-edit/<int:pk>', views.InstansiUpdateView.as_view(), name='instansi_edit'),

  path('suratmasuk-list/', views.SMListView.as_view(), name='sm_list'),
  path('suratmasuk-form/', views.SMCreateView.as_view(), name='sm_form'),
  path('suratmasuk-delete/<int:id>', views.SMDeleteView.as_view(), name='sm_delete'),
  path('suratmasuk-edit/<int:id>', views.SMUpdateView.as_view(), name='sm_edit'),

  path('suratkeluar-list/', views.SKListView.as_view(), name='sk_list'),
  path('suratkeluar-form/', views.SKCreateView.as_view(), name='sk_form'),
  path('suratkeluar-delete/<int:id>', views.SKDeleteView.as_view(), name='sk_delete'),
  path('suratkeluaredit/<int:id>', views.SKUpdateView.as_view(), name='sk_edit'),
]

administrasi/surat_menyurat/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Instansi(models.Model):
  KATEGORI_INSTANSI = (
    ('swasta', 'Swasta'),
    ('pemerintah', 'Pemerintah'),
  )

  nama_instansi = models.CharField(max_length=255, blank=False, null=False)
  kategori      = models.CharField(max_length=255, choices=KATEGORI_INSTANSI)
  telepon       = models.CharField(max_length=255, blank=True, null=True)
  kode_pos      = models.CharField(max_length=255, blank=True, null=True)
  alamat        = models.TextField(blank=True, null=True)
  created       = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated       = models.DateTimeField(auto_now=True, auto_now_add=False)

  def __str__(self):
    return self.nama_instansi

class Surat(models.Model):
  nomor         = models.CharField(max_length=255, blank=False, null=False)
  tgl_surat     = models.CharField(
                  _("Tanggal surat"),
                  help_text=_('Tanggal di dalam isi surat'),
                  max_length=255, blank=False, null=False)
  perihal       = models.CharField(max_length=255, blank=False, null=False)
  pengirim      = models.CharField(
                  help_text=_('Orang atau jasa yang mengantar surat'),
                  max_length=255, blank=True, null=True)
  deskripsi     = models.TextField(blank=True, null=True)

class SuratMasuk(Surat):
  asal_instansi = models.ForeignKey(
                  Instansi,
                  help_text=_('Jika asal instansi tidak ada, silahkan ke menu instansi'),
                  on_delete=models.CASCADE)
  tgl_masuk     = models.CharField(
                  _("Tanggal masuk"),
                  help_text=_('Tanggal masuk surat ke kantor'),
                  max_length=255, blank=False, null=False)
  created       = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated       = models.DateTimeField(auto_now=True, auto_now_add=False)

  def __str__(self):
    return self.nomor

class SuratKeluar(Surat):
  tujuan_instansi   = models.ForeignKey(
                      Instansi,
                      help_text=_('Jika tujuan instansi tidak ada, silahkan ke menu instansi'),
                      on_delete=models.CASCADE)
  tgl_keluar        = models.CharField(
                      _("Tanggal keluar"),
                      help_text=_('Tanggal keluar surat dari kantor'),
                      max_length=255, blank=False, null=False)
  created           = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated           = models.DateTimeField(auto_now=True, auto_now_add=False)

  def __str__(self):
    return self.nomor

administrasi/surat_menyurat/forms.py
from django import forms
from surat_menyurat.models import Instansi, SuratMasuk, SuratKeluar

class FormSuratMasuk(forms.ModelForm):
  class Meta:
    model = SuratMasuk
    exclude = ('id', )

  def __init__(self, *args, **kwargs):
    super(FormSuratMasuk, self).__init__(*args, **kwargs)
    for visible in self.visible_fields():
      visible.field.widget.attrs['class'] = 'form-control form-control-sm'
    
class FormSuratKeluar(forms.ModelForm):
  class Meta:
    model = SuratKeluar
    exclude = ('id', )

  def __init__(self, *args, **kwargs):
    super(FormSuratKeluar, self).__init__(*args, **kwargs)
    for visible in self.visible_fields():
      visible.field.widget.attrs['class'] = 'form-control form-control-sm'
      
class FormInstansi(forms.ModelForm):
  class Meta:
    model = Instansi
    exclude = ('id', )

  def __init__(self, *args, **kwargs):
    super(FormInstansi, self).__init__(*args, **kwargs)
    for visible in self.visible_fields():
      visible.field.widget.attrs['class'] = 'form-control form-control-sm'

administrasi/surat_menyurat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, View, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from surat_menyurat.models import SuratMasuk, SuratKeluar, Instansi
from surat_menyurat.forms import FormSuratMasuk, FormInstansi, FormSuratKeluar

@login_required
def home(request):
   return render(request, 'home.html')

def login_redirect(request):
   return redirect('login')

class InstansiUpdateView(LoginRequiredMixin, UpdateView):
   model = Instansi
   form_class = FormInstansi
   template_name = 'instansi/form_edit.html'

   def form_valid(self, form):
      self.object = form.save(commit=False)
      self.object.save()
      return redirect("surat:instansi_list")

   @method_decorator(login_required)
   def dispatch(self, request, *args, **kwargs):
      return super(InstansiUpdateView, self).dispatch(request, *args, **kwargs)

class InstansiListView(LoginRequiredMixin, ListView):
   queryset = Instansi.objects.all()
   template_name='instansi/instansi_list.html'

class InstansiCreateView(LoginRequiredMixin, CreateView):
   form_class = FormInstansi
   template_name = 'instansi/form_new.html'
   success_url = reverse_lazy('surat:instansi_list')

class InstansiDeleteView(LoginRequiredMixin, View):
   def get(self, r, id):
      instansi = get_object_or_404(Instansi, id=id)
      instansi.delete()
      return redirect('surat:instansi_list')

class SMUpdateView(LoginRequiredMixin, UpdateView):
   model = SuratMasuk
   form_class = FormSuratMasuk
   template_name = 'surat/sm_edit.html'

   def form_valid(self, form):
      self.object = form.save(commit=False)
      self.object.save()
      return redirect("surat:sm_list")

   @method_decorator(login_required)
   def dispatch(self, request, *args, **kwargs):
      return super(SMUpdateView, self).dispatch(request, *args, **kwargs)

class SMListView(LoginRequiredMixin, ListView):
   queryset = SuratMasuk.objects.all()
   template_name='surat/sm_list.html'

class SMCreateView(LoginRequiredMixin, CreateView):
   form_class = FormSuratMasuk
   template_name = 'surat/sm_new.html'
   success_url = reverse_lazy('surat:sm_list')

class SMDeleteView(LoginRequiredMixin, View):
   def get(self, r, id):
      sm = get_object_or_404(SuratMasuk, id=id)
      sm.delete()
      return redirect('surat:sm_list')

class SKUpdateView(LoginRequiredMixin, UpdateView):
   model = SuratKeluar
   form_class = FormSuratKeluar
   template_name = 'surat/sk_edit.html'

   def form_valid(self, form):
      self.object = form.save(commit=False)
      self.object.save()
      return redirect("surat:sk_list")

   @method_decorator(login_required)
   def dispatch(self, request, *args, **kwargs):
      return super(SKUpdateView, self).dispatch(request, *args, **kwargs)

class SKListView(LoginRequiredMixin, ListView):
   queryset = SuratKeluar.objects.all()
   template_name='surat/sk_list.html'

class SKCreateView(LoginRequiredMixin, CreateView):
   form_class = FormSuratKeluar
   template_name = 'surat/sk_new.html'
   success_url = reverse_lazy('surat:sk_list')

class SKDeleteView(LoginRequiredMixin, View):
   def get(self, r, id):
      sk = get_object_or_404(SuratKeluar, id=id)
      sk.delete()
      return redirect('surat:sk_list')

administrasi/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="icon" href="https://itec.sch.id/wp-content/uploads/2018/05/itec-pav.png">
  <title>Aplikasi administrasi surat menyurat</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>
</head>
<style>
  .content{
    margin-left:10px
  }
  .footer{
    clear: both;
    position: relative;
    height: 40px;
    margin-top: 100px;
  }
  table{
    font-size:14px;
  }
</style>
<body>
  {% include "navbar.html" %}
  <div class="container">
  <h3 style="margin:30px 0px 30px 0px">
    Aplikasi
    <small class="text-muted">administrasi surat menyurat</small>
  </h3>
  {% block content %}
    
  {% endblock content %}
  </div>
  <div class="footer">
    <p class="mt-5 mb-3 text-muted text-center">
      <a href="https://itec.sch.id" target="blank">ITEC</a> &copy; 2018</p>
  </div>
</body>
</html>

administrasi/templates/home.html
{% extends "base.html" %}
{% block content %}
  <p>Hello {{user.username}}</p>
{% endblock content %}  

administrasi/templates/instansi/form_edit.html
{% extends "base.html" %}

{% block content %}
  <h4>
    <small class="text-muted">Form edit instansi</small>
    <small class="text-muted" style="float:right">
      <a href="{% url 'surat:instansi_list' %}">List data</a>
    </small>
  </h4>
  <form action="" method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover">
      <input type="hidden" value="{{ id }}" name="id" />
        {{form.as_table}}
      </table>
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
{% endblock content %}

administrasi/templates/instansi/form_new.html
{% extends "base.html" %}

{% block content %}
  <h4>
    <small class="text-muted">Form instansi</small>
    <small class="text-muted" style="float:right">
      <a href="{% url 'surat:instansi_list' %}">List data</a>
    </small>
  </h4>
  <form action="" method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover">
      {{form.as_table}}
    </table>
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
{% endblock content %}

administrasi/templates/instansi/instansi_list.html
{% extends "base.html" %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">List</li>
      <li class="breadcrumb-item"><a href="{% url 'surat:instansi_form' %}">Form</a></li>
    </ol>
  </nav>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nama Instansi</th>
        <th scope="col">Kategori</th>
        <th scope="col">Telepon</th>
        <th scope="col">Kode Pos</th>
        <th scope="col">Alamat</th>
        <th scope="col">Date</th>
        <th scope="col">#</th>
      </tr>
    </thead>
    {% for dt in object_list %}
      <tbody>
        <tr>
          <td scope="col">{{ forloop.counter }} .</td>
          <td scope="row">{{ dt.nama_instansi }}</td>
          <td>{{dt.kategori}}</td>
          <td>{{dt.telepon}}</td>
          <td>{{dt.kode_pos}}</td>
          <td>{{dt.alamat}}</td>
          <td>{{dt.created|timesince}}</td>
          <td>
            <a class="btn btn-warning btn-sm" href="{% url 'surat:instansi_edit' dt.id %}">Edit</a> | 
            <a class="btn btn-danger btn-sm" onclick="return confirm('Delete data?')" href="{% url 'surat:instansi_delete' dt.id %}">Hapus</a>
          </td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock content %}  

administrasi/templates/instansi/list.html
{% extends "base.html" %}

{% block content %}
  <h4>
    <small class="text-muted">List instansi</small>
    <small class="text-muted" style="float:right">
      <a href="{% url 'surat:instansi_form' %}">Add data</a>
    </small>
  </h4>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nama Instansi</th>
        <th scope="col">Kategori</th>
        <th scope="col">Telepon</th>
        <th scope="col">Kode Pos</th>
        <th scope="col">Alamat</th>
        <th scope="col">Date</th>
        <th scope="col">#</th>
      </tr>
    </thead>
    {% for dt in data %}
      <tbody>
        <tr>
          <td scope="col">{{ forloop.counter }} .</td>
          <td scope="row">{{ dt.nama_instansi }}</td>
          <td>{{dt.kategori}}</td>
          <td>{{dt.telepon}}</td>
          <td>{{dt.kode_pos}}</td>
          <td>{{dt.alamat}}</td>
          <td>{{dt.created|timesince}}</td>
          <td>
            <a href="{% url 'surat:instansi_edit' dt.id %}">Edit</a> | 
            <a onclick="return confirm('Delete data?')" href="{% url 'surat:instansi_delete' dt.id %}">Hapus</a>
          </td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock content %}  

administrasi/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">ITEC Mataram</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Instansi
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'surat:instansi_list' %}">List</a>
          <a class="dropdown-item" href="{% url 'surat:instansi_form' %}">Add new</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Surat Masuk
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'surat:sm_list' %}">List</a>
          <a class="dropdown-item" href="{% url 'surat:sm_form' %}">Add new</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Surat Keluar
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'surat:sk_list' %}">List</a>
          <a class="dropdown-item" href="{% url 'surat:sk_form' %}">Add new</a>
        </div>
      </li>
      <li class="nav-item nav-right">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>

administrasi/templates/surat/sk_edit.html
{% extends "base.html" %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'surat:sk_list' %}">List</a></li>
      <li class="breadcrumb-item"><a href="{% url 'surat:sk_form' %}">New</a></li>
      <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
  </nav>
  <form action="{" method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover">
      <input type="hidden" value="{{ id }}" name="id" />
        {{form.as_table}}
      </table>
    <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
  </form>
{% endblock content %}

administrasi/templates/surat/sk_list.html
{% extends "base.html" %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">List</li>
      <li class="breadcrumb-item"><a href="{% url 'surat:sk_form' %}">New</a></li>
    </ol>
  </nav>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nomor</th>
        <th scope="col">Tanggal surat</th>
        <th scope="col">Perihal</th>
        <th scope="col">Pengirim/Jasa</th>
        <th scope="col">Deksripsi</th>
        <th scope="col">Tujuan instansi</th>
        <th scope="col">Tanggal keluar</th>
        <th scope="col">Tanggal keluar</th>
        <th scope="col">Date</th>
        <th scope="col">#</th>
      </tr>
    </thead>
    {% for dt in object_list %}
      <tbody>
        <tr>
          <td scope="col">{{ forloop.counter }}</td>
          <td scope="row">{{ dt.nomor }}</td>
          <td>{{dt.tgl_surat}}</td>
          <td>{{dt.perihal}}</td>
          <td>{{dt.pengirim}}</td>
          <td>{{dt.deskripsi}}</td>
          <td>{{dt.tujuan_instansi}}</td>
          <td>{{dt.tgl_keluar}}</td>
          <td>{{dt.created|timesince}}</td>
          <td>
            <a class="btn btn-warning btn-sm" href="{% url 'surat:sk_edit' dt.id %}">Edit</a> | 
            <a class="btn btn-danger btn-sm" onclick="return confirm('Delete data?')" href="{% url 'surat:sk_delete' dt.id %}">Hapus</a>
          </td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock content %}

administrasi/templates/surat/sk_new.html
{% extends "base.html" %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'surat:sk_list' %}">List</a></li>
      <li class="breadcrumb-item active" aria-current="page">New</li>
    </ol>
  </nav>
  <form action="" method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover">
      {{form.as_table}}
    </table>
    <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
  </form>

  <script>
    $(function() {
      $("#id_tgl_keluar").datepicker({
        dateFormat: 'dd-mm-yy'
      });
      $("#id_tgl_surat").datepicker({
        dateFormat: 'dd-mm-yy'
      });
    });
  </script>
{% endblock content %}

administrasi/templates/surat/sm_edit.html
{% extends "base.html" %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'surat:sk_list' %}">List</a></li>
      <li class="breadcrumb-item"><a href="{% url 'surat:sk_form' %}">New</a></li>
      <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
  </nav>
  <form action="" method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover">
      <input type="hidden" value="{{ id }}" name="id" />
        {{form.as_table}}
      </table>
    <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
  </form>
{% endblock content %}

administrasi/templates/surat/sm_list.html
{% extends "base.html" %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">List</li>
      <li class="breadcrumb-item"><a href="{% url 'surat:sm_form' %}">New</a></li>
    </ol>
  </nav>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nomor</th>
        <th scope="col">Tanggal surat</th>
        <th scope="col">Perihal</th>
        <th scope="col">Pengirim/Jasa</th>
        <th scope="col">Deksripsi</th>
        <th scope="col">Asal instansi</th>
        <th scope="col">Tanggal masuk</th>
        <th scope="col">Date</th>
        <th scope="col">#</th>
      </tr>
    </thead>
    {% for dt in object_list %}
      <tbody>
        <tr>
          <td scope="col">{{ forloop.counter }}</td>
          <td scope="row">{{ dt.nomor }}</td>
          <td>{{dt.tgl_surat}}</td>
          <td>{{dt.perihal}}</td>
          <td>{{dt.pengirim}}</td>
          <td>{{dt.deskripsi}}</td>
          <td>{{dt.asal_instansi}}</td>
          <td>{{dt.tgl_masuk}}</td>
          <td>{{dt.created|timesince}}</td>
          <td>
            <a class="btn btn-warning btn-sm" href="{% url 'surat:sm_edit' dt.id %}">Edit</a> | 
            <a class="btn btn-danger btn-sm" onclick="return confirm('Delete data?')" href="{% url 'surat:sm_delete' dt.id %}">Hapus</a>
          </td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock content %}

administrasi/templates/surat/sm_new.html
{% extends "base.html" %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'surat:sm_list' %}">List</a></li>
      <li class="breadcrumb-item active" aria-current="page">New</li>
    </ol>
  </nav>
  <form action="" method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover">
      {{ form.as_table }}
    </table>
    <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
  </form>

  <script>
    $(function() {
      $("#id_tgl_masuk").datepicker({
        dateFormat: 'dd-mm-yy'
      });
      $("#id_tgl_surat").datepicker({
        dateFormat: 'dd-mm-yy'
      });
    });
  </script>
{% endblock content %}

administrasi/templates/surat/surat_keluar_form_new.html
{% extends "base.html" %}

{% block content %}
  <h4>
    <small class="text-muted">Form surat keluar</small>
    <small class="text-muted" style="float:right">
      <a href="{% url 'surat:surat_keluar_list' %}">List data</a>
    </small>
  </h4>
  <form action="" method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover">
      {{form.as_table}}
    </table>
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>

  <script>
    $(function() {
      $("#id_tgl_keluar").datepicker({
        dateFormat: 'dd-mm-yy'
      });
      $("#id_tgl_surat").datepicker({
        dateFormat: 'dd-mm-yy'
      });
    });
  </script>
{% endblock content %}

administrasi/templates/surat/surat_keluar_list.html
{% extends "base.html" %}

{% block content %}
  <h4>
    <small class="text-muted">List surat masuk</small>
    <small class="text-muted" style="float:right">
      <a href="{% url 'surat:surat_keluar_form' %}">Add data</a>
    </small>
  </h4>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nomor</th>
        <th scope="col">Tanggal surat</th>
        <th scope="col">Perihal</th>
        <th scope="col">Pengirim/Jasa</th>
        <th scope="col">Deksripsi</th>
        <th scope="col">Tujuan instansi</th>
        <th scope="col">Tanggal keluar</th>
        <th scope="col">Tanggal keluar</th>
        <th scope="col">Date</th>
        <th scope="col">#</th>
      </tr>
    </thead>
    {% for dt in data %}
      <tbody>
        <tr>
          <td scope="col">{{ forloop.counter }}</td>
          <td scope="row">{{ dt.nomor }}</td>
          <td>{{dt.tgl_surat}}</td>
          <td>{{dt.perihal}}</td>
          <td>{{dt.pengirim}}</td>
          <td>{{dt.deskripsi}}</td>
          <td>{{dt.tujuan_instansi}}</td>
          <td>{{dt.tgl_keluar}}</td>
          <td>{{dt.created|timesince}}</td>
          <td>
            <a href="{% url 'surat:surat_keluar_edit' dt.id %}">Edit</a> | 
            <a onclick="return confirm('Delete data?')" href="{% url 'surat:surat_keluar_delete' dt.id %}">Hapus</a>
          </td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock content %}

administrasi/templates/surat/surat_masuk_form_new.html
{% extends "base.html" %}

{% block content %}
  <h4>
    <small class="text-muted">Form surat masuk</small>
    <small class="text-muted" style="float:right">
      <a href="{% url 'surat:surat_masuk_list' %}">List data</a>
    </small>
  </h4>
  <form action="" method="post">
    {% csrf_token %}
    <table class="table table-striped table-hover">
      {{form.as_table}}
    </table>
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>

  <script>
    $(function() {
      $("#id_tgl_masuk").datepicker({
        dateFormat: 'dd-mm-yy'
      });
      $("#id_tgl_surat").datepicker({
        dateFormat: 'dd-mm-yy'
      });
    });
  </script>
{% endblock content %}